---

- name: Install etcd package 
  zypper:
    name: etcd
    state: present

- name: Install etcd package 
  zypper:
    name: etcdctl
    state: present

- name: Configure etcdctl sysconfig
  template: 
    src: etcd.j2
    dest: /etc/sysconfig/etcd

- name: Enable and start etcd
  service:
    name: etcd
    state: started
