---

- name: Check if Jira service is running
  shell: docker service ls | awk '{print $2}' | grep jira
  changed_when: jira_status.rc == 1
  ignore_errors: true
  failed_when: jira_status.rc == 2
  register: jira_status 

- name: Create jira volume root directory
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/jira
    state: directory
    mode: 777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Create jira volume data directory
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/jira/data
    state: directory
    mode: 777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Create jira volume logs directory
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/jira/logs
    state: directory
    mode: 777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Deploy jira service
  hosts: docker-manager[0]
  shell: docker service create -d --name jira --network mangonet --mount type=bind,src=/srv/docker-volumes/jira/data,dst=/var/atlassian/jira --mount type=bind,src=/srv/docker-volumes/jira/logs,dst=/opt/atlassian/jira/logs --replicas 1 registry.sysmango.net:5000/jira
  run_once: true
  when: jira_status.rc == 1
