---

- name: Check if Jira service is running
  shell: docker service ls | awk '{print $2}' | grep jira
  ignore_errors: true
  register: jira_status
  changed_when: jira_status.rc == 1
  failed_when: jira_status.rc == 2

- name: Create jira volume root directory
  become: "yes"
  file:
    path: /srv/nfs/jira
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Create jira volume data directory
  become: "yes"
  file:
    path: /srv/nfs/jira/data
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Create jira volume logs directory
  become: "yes"
  file:
    path: /srv/nfs/jira/logs
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: jira_status.rc == 1

- name: Deploy jira service
  command: |
    docker service create -d --name jira \
    --network mangonet \
    --label traefik.port=8080 \
    --mount type=bind,src=/srv/docker-volumes/jira/data,dst=/var/atlassian/jira \
    --mount type=bind,src=/srv/docker-volumes/jira/logs,dst=/opt/atlassian/jira/logs \
    --replicas 1 \
    registry.sysmango.net/sysmango/jira:latest
  run_once: true
  when: jira_status.rc == 1
