---

- name: Do route53 work
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
  - route53-smtp

- name: Deploy docker services
  hosts: docker-manager[0]
  gather_facts: yes
  roles:
  - traefik-service
  - docker-viz-service
  - nexus-service
  - smtp-service
  - elk-service
  - database-service
  - redis-service
  - jira-service
  - jenkins-service
  - nextcloud-service
  - monitoring-service
  # - reverseproxy-service
