---

# ---
# SLAM_TASKNAME: SYSMANGO DOCKER SERVICES PLAYBOOK
# SLAM_FACT_SYSTEM: Linux
# SLAM_Q: [ play,triage ]
# SLAM_FF_TARGET:
#   type: Integer
#   required: false
#   prompt: Enter the target
#   ghost: eg www.google.com
#   default: www.csc.com
#   tooltip: Target Name
# SLAM_FF_NUMTRIES:
#   type: Integer
#   required: true
#   prompt: Enter the Number of tries
#   default: 3
# ---

- name: Setup docker services environments
  hosts: nfs_server
  gather_facts: true
  roles:
  - sonarqube-setup

- name: Deploy docker services
  hosts: leader
  gather_facts: true
  roles:
  - traefik-service
  - docker-viz-service
  - nexus-service
  - smtp-service
  - database-service
  - redis-service
  - jira-service
  - jenkins-service
  - nextcloud-service
  - sonarqube-service
  #  - elastic-service
  #  - monitoring-service
