---

- src: git+git@bitbucket.org:sysmango/nextcloud-service.git
  path: roles
  name: nextcloud-service

- src: git+git@bitbucket.org:sysmango/traefik-service.git
  path: roles
  name: traefik-service

- src: git+git@bitbucket.org:sysmango/vault-service.git
  path: roles
  name: vault-service

- src: git+git@bitbucket.org:sysmango/elastic-service.git
  path: roles
  name: elastic-service

- src: git+git@bitbucket.org:sysmango/raffia-service.git
  path: roles
  name: raffia-service

