---
#- src: git+git@github.com:sysmango/nextcloud-service.git
#  path: roles
#  name: nextcloud-service

  #- src: http://nexus.sysmango.net/repository/ansible/prod/database-service.tar.gz
  #path: roles
  #name: database-service

# - src: git+git@bitbucket.org:butch/traefik-service.git
#   path: roles
#   name: traefik-service

# - src: git+git@bitbucket.org:butch/elastic-service.git
#   path: roles
#   name: elastic-service

- src: git+git@github.com:butchlebo/sonarqube-setup.git
  path: roles
  name: sonarqube-setup

- src: git+git@github.com:butchlebo/sonarqube-service.git
  path: roles
  name: sonarqube-service