---
- name: Bootstrap new sysmango servers.
  hosts: all
  become: yes
  gather_facts: no
  roles:
  - sysmango-bootstrap

- name: Install Docker packages.
  hosts: all
  become: yes
  gather_facts: no
  roles:
  - docker-install

- name: Install etcd packages.
  hosts: all
  become: yes
  gather_facts: yes
  roles:
  - etcd-install

- import_playbook: swarm.yml
