---

- name: Bootstrap new sysmango servers.
  hosts: all
  become: "true"
  gather_facts: "true"
  roles:
  - sysmango-bootstrap

- name: Install Docker packages.
  hosts: docker
  become: "true"
  gather_facts: "no"
  roles:
  - docker-install

# - name: Install and configure etcd packages.
#   hosts: all
#   become: "true"
#   gather_facts: "true"
#   roles:
#   - etcd-install

# - name: Install and configure flannel packages.
#   hosts: all
#   become: "true"
#   gather_facts: "true"
#   roles:
#   - flannel-install

- name: Enable and start Docker
  hosts: docker
  become: "true"
  tasks:
  - name: Docker Service
    service:
      name: docker
      state: started
      enabled: "true"

- import_playbook: swarm.yml

- name: Setup NFS server
  hosts: nfs_server
  become: "true"
  gather_facts: "no"
  roles:
    - nfs-server

- name: Setup NFS clients
  hosts: nfs_client
  become: "true"
  gather_facts: "no"
  roles:
    - nfs-client

- name: Setup Swarm overlay network
  hosts: docker_manager[0]
  roles:
    - mangonet
