---

- name: Bootstrap new sysmango servers.
  hosts: all
  become: yes
  gather_facts: yes
  roles:
  - sysmango-bootstrap

- name: Install Docker packages.
  hosts: all
  become: yes
  gather_facts: no
  roles:
  - docker-install

# - name: Install and configure etcd packages.
#   hosts: all
#   become: yes
#   gather_facts: yes
#   roles:
#   - etcd-install

# - name: Install and configure flannel packages.
#   hosts: all
#   become: yes
#   gather_facts: yes
#   roles:
#   - flannel-install

- name: Enable and start Docker
  hosts: all
  become: yes
  tasks:
  - name: Docker Service 
    service:
      name: docker
      state: started
      enabled: yes

- import_playbook: swarm.yml

- name: Setup NFS server
  hosts: nfs-server
  become: yes
  gather_facts: no
  roles:
  - nfs-server

# - name: Setup NFS clients
#   hosts: all
#   become: yes
#   gather_facts: no
#   roles:
#   - nfs-client

- name: Setup Swarm overlay network
  hosts: docker-manager
  roles:
  - mangonet

# - name: Deploy SMTP service to swarm
#   hosts: docker-manager
#   gather_facts: no
#   roles:
#   - smtp-service
#   - registry-service
#   - database-service
