--- 

- name: Check SMTP service status
  hosts: docker-manager[0]
  tasks:
  - name: run command
    shell: docker service ls | awk '{print $2}' | grep smtp
    register: service_status
    changed_when: false
    failed_when: service_staus.rc  > 2

  - name: echo outcome
    debug: 
      msg: "Hello, WOrld!"
    when: "{{ service_status|changed }}"

