---

- name: Check if traefik service is running
  shell: docker service ls | awk '{print $2}' | grep traefik
  changed_when: traefik_status.rc == 1
  ignore_errors: true
  failed_when: traefik_status.rc == 2
  register: traefik_status

# - name: Check if traefik-net is available
#   shell: docker network ls | awk '{print $2}' | grep traefik-net
#   changed_when: traefiknet_status.rc == 1
#   ignore_errors: true
#   failed_when: traefiknet_status.rc == 2
#   register: traefiknet_status

# - name: Create traefik-net overlay network
#   hosts: docker-manager[0]
#   docker_network:
#     name: traefik-net
#     driver: overlay
#     state: present
#   when: traefiknet_status.rc == 1

- name: Deploy traefik service
  command: |
    docker service create \
    --name traefik \
    --constraint=node.role==manager \
    --publish 80:80 --publish 8080:8080 --publish=443:443 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --network mangonet \
    traefik \
    --docker \
    --docker.swarmmode \
    --docker.domain=sysmango.net \
    --docker.watch \
    --api
  when: traefik_status.rc == 1

- name: Wait for traefik to allow connections
  wait_for:
    port: 8080
    timeout: 5000
