---

- name: Check if Docker Registry service is running
  shell: docker service ls | awk '{print $2}' | grep registry
  changed_when: true
  register: registry_status
  failed_when: registry_status.rc == 2

- name: setup daemon.json
  become: yes
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: registry_status|changed

- name: Deploy insecure docker registry service
  hosts: docker-manager
  shell: docker service create -d --name registry --mount type=bind,src=/srv/docker-volumes/registry,dst=/var/lib/registry --publish published=5000,target=5000 --replicas 1 registry:2
  when: registry_status|changed
