---

- name: Check if Docker Registry service is running
  command: docker service ls | awk '{print $2}' | grep registry
  changed_when: false
  register: registry_status
  failed_when: registry_status.rc == 2

- name: setup daemon.json
  become: yes
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Deploy insecure docker registry service
  hosts: docker-manager
  command: |
    docker service create -d --name registry --network mangonet --mount type=bind,src=/srv/docker-volumes/registry,dst=/var/lib/registry --publish 5000:5000 --env REGISTRY_HTTP_SECRET=14aff6229ebd9c59496fe203cf20e23868266e9bc11e114ad22bd82486035e37 --replicas 1 registry:2
  when: registry_status.rc == 1

