---

- name: Check if owncloud service is running
  command: docker service ls | awk '{print $2}' | grep owncloud
  changed_when: owncloud_status.rc == 1
  ignore_errors: true
  failed_when: owncloud_status.rc == 2
  register: owncloud_status 

- name: Create owncloud volume root directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/owncloud
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: owncloud_status.rc == 1

- name: Create owncloud volume data directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/owncloud/data
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: owncloud_status.rc == 1

# - name: Create owncloud volume config directory
#   hosts: nfs-server[0]
#   become: "yes"
#   file:
#     path: /srv/nfs/owncloud/config
#     state: directory
#     mode: 0777
#   any_errors_fatal: true
#   when: owncloud_status.rc == 1

- name: Create owncloud db user
  connection: local
  postgresql_user: 
    login_host: postgres
    login_password: dbadmin
    user: owncloud
    password: 'str[\"md5\"] + md5[ owncloudadmin + owncloud ]'
    encrypted: "yes"
    state: present
  when: owncloud_status.rc == 1

- name: Setup owncloud database on db server
  connection: local
  postgresql_db:
    login_host: postgres
    login_password: dbadmin
    name: owncloud
    owner: owncloud
    state: present
  when: owncloud_status.rc == 1

- name: Deploy owncloud service
  hosts: docker-manager[0]
  command: | 
    docker service create -d --name owncloud \
    --network mangonet \
    --mount type=bind,src=/srv/docker-volumes/owncloud/data,dst=/mnt/data \
    -e OWNCLOUD_DOMAIN=sysmango.net\
    -e OWNCLOUD_DB_TYPE=pgsql \
    -e OWNCLOUD_DB_USERNAME=owncloud \
    -e OWNCLOUD_DB_PASSWORD=owncloudadmin \
    -e OWNCLOUD_DB_HOST=postgres \
    -e OWNCLOUD_ADMIN_USERNAME=sysmango \
    -e OWNCLOUD_ADMIN_PASSWORD=Atr0c1ty! \
    -e OWNCLOUD_REDIS_ENABLED=true \
    -e OWNCLOUD_REDIS_HOST=redis \
    --replicas 1 \
    owncloud/server  
  run_once: true
  when: owncloud_status.rc == 1

- name: Register owncloud name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: owncloud.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.200
    overwrite: "yes"
    wait: "yes"