---

- name: Check if elasticsearch service is running
  shell: docker service ls | awk '{print $2}' | grep elasticsearch
  changed_when: false
  register: elastic_status
  failed_when: elastic_status.rc == 2

- name: Create volume directory for elk
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk
    state: directory
    mode: 0777
  when: elastic_status.rc == 1

- name: Create volume directory for elasticsearch
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk/elasticsearch
    state: directory
    mode: 0777
  when: elastic_status.rc == 1


- name: Deploy elasticsearch service
  hosts: docker-manager
  shell: |
    docker service create -d \
    --name elasticsearch \
    --network mangonet \
    --mount type=bind,src=/srv/docker-volumes/elk/elasticsearch,dst=/usr/share/elasticsearch/data \
    --replicas 1 \
    --publish 9200:9200 --publish 9300:9300 -e "discovery.type=single-node" \
    docker.elastic.co/elasticsearch/elasticsearch:6.1.2
  when: elastic_status.rc == 1  

- name: Register elastic name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: elastic.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.200
    overwrite: yes
    wait: yes

- name: Check if kibana service is running
  shell: docker service ls | awk '{print $2}' | grep kibana
  changed_when: false
  register: kibana_status
  failed_when: kibana_status.rc == 2

- name: Create volume directory for kibana
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk/kibana
    state: directory
    mode: 0777
  when: kibana_status.rc == 1

- name: Create volume directory for kibana
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk/kibana/data
    state: directory
    mode: 0777
  when: kibana_status.rc == 1


- name: Deploy kibana service
  hosts: docker-manager
  shell: |
    docker service create -d \
    --name kibana \
    --network mangonet \
    --publish 5601:5601 \
    --mount type=bind,src=/srv/docker-volumes/elk/kibana/data,dst=/var/lib/kibana \
    --replicas 1 \
    docker.elastic.co/kibana/kibana:6.1.2
  when: kibana_status.rc == 1

# Defaults
# --env=SERVER_NAME=kibana.sysmango.net
# --env=ELASTICSEARCH_URL=http://elasticsearch
# Not working


- name: Register kibana name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: kibana.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.200
    overwrite: yes
    wait: yes

- name: Check if logstash service is running
  shell: docker service ls | awk '{print $2}' | grep logstash
  changed_when: false
  register: logstash_status
  failed_when: logstash_status.rc == 2

- name: Create volume directory for logstash
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk/logstash
    state: directory
    mode: 0777
  when: logstash_status.rc == 1

- name: Create volume directory for logstash
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/elk/logstash/pipeline
    state: directory
    mode: 0777
  when: logstash_status.rc == 1


- name: Deploy logstash service
  hosts: docker-manager
  shell: |
    docker service create -d \
    --name logstash \
    --network mangonet \
    --publish 5044:5044 --publish 9600:9600 \
    --mount type=bind,src=/srv/docker-volumes/elk/logstash/pipeline/,dst=/usr/share/logstash/pipeline/ \
    --replicas 1 \
    docker.elastic.co/logstash/logstash:6.1.2
  when: logstash_status.rc == 1

- name: Register logstash name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: logstash.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.200
    overwrite: yes
    wait: yes
