---

- name: Check if Jenkins service is running
  shell: docker service ls | awk '{print $2}' | grep jenkins
  changed_when: false
  ignore_errors: true
  failed_when: jenkins_status.rc == 2
  register: jenkins_status

- name: Create jenkins volume directory
  become: "true"
  file:
    path: /srv/nfs/jenkins
    mode: 0777
    state: directory
  run_once: true
  when: jenkins_status.rc == 1

- name: Deploy jenkins service
  command: |
    docker service create -d --name jenkins \
    --network mangonet \
    --label traefik.port=8080 \
    --label traefik.enable=true \
    --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/jenkins,volume-opt=type=nfs,target=/var/jenkins_home' \
    --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    --constraint=node.role==manager \
    --replicas 1 \
    jenkinsci/blueocean:latest
  run_once: true
  when: jenkins_status.rc == 1

# - uri:
#   url: http://jenkins.sysmango.net
#   status_code: 200
#   timeout: 3000
#   register: is_jenkinsup
