---

- name: Check if Docker Visualizer service is running
  shell: docker service ls | awk '{print $2}' | grep viz
  changed_when: false
  register: viz_status
  failed_when: viz_status.rc == 2

- name: Deploy Docker Visualizer service
  hosts: docker-manager
  command: |
    docker service create \
    --name=viz \
    --network=mangonet \
    --label traefik.port=8080 \
    --constraint=node.role==manager \
    --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    dockersamples/visualizer
  when: viz_status.rc == 1

- name: Register viz name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: viz.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.201
    overwrite: "yes"
    wait: "yes"