---

- name: Check if Docker Visualizer service is running
  shell: docker service ls | awk '{print $2}' | grep viz
  changed_when: false
  register: viz_status
  failed_when: viz_status.rc == 2

# - name: Deploy Docker Visualizer service
#   command: |
#     docker service create \
#     --name=viz \
#     --network=mangonet \
#     --label traefik.port=8080 \
#     --constraint=node.role==manager \
#     --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
#     dockersamples/visualizer
#   when: viz_status.rc == 1

# - name: Register viz name with Route53
#   connection: local
#   route53:
#     state: present
#     zone: sysmango.net
#     record: viz.sysmango.net
#     type: A
#     value: 192.168.1.144,192.168.1.225,192.168.1.200
#     overwrite: "yes"
#     wait: "yes"

- name: Deploy Docker Visualizer service
  docker_swarm_service:
    debug: yes
    name: viz
    image: dockersamples/visualizer
    networks:
    - mangonet
    labels:
      "traefik.port=8080"
    constraints:
    - "node.role==manager"
    mounts:
    - type: bind
      source: "/var/run/docker.sock"
      target: "/var/run/docker.sock"
    docker_host: tcp://sysmango.net:2375
  when: viz_status.rc == 1