---

- name: Setup NFS client mount point for volumes
  become: "true"
  file:
    path: /srv/docker-volumes
    state: directory
    mode: 0777

- name: Mount NFS volume root
  become: "true"
  mount:
    path: /srv/docker-volumes
    src: files.sysmango.net:/srv/nfs
    fstype: nfs
    opts: rw
    state: mounted

- name: Make sure NFS mounts will mount on startup
  become: "true"
  service:
    name: nfs
    state: started
    enabled: "true"
