---

- name: Check if reverseproxy service is running
  shell: docker service ls | awk '{print $2}' | grep reverseproxy
  changed_when: false
  ignore_errors: true
  failed_when: reverseproxy_status.rc == 2
  register: reverseproxy_status 

- name: Deploy reverseproxy service
  hosts: docker-manager[0]
  shell: |
    docker service create \
    --name reverseproxy \
    --network mangonet \
    --publish 80:80 \
    --publish 443:443 \
    --mode global \
    nexus.sysmango.net/reverseproxy
  run_once: true
  when: reverseproxy_status.rc == 1

- name: Install SysMango Root cert
  copy: 
    src: SysMangoRootCA.crt 
    dest: /usr/share/pki/trust/anchors/SysMangoRootCA.crt 

- name: Install SysMango Intermediate cert
  copy: 
    src: SysMangoIntermediateCA.crt 
    dest: /usr/share/pki/trust/anchors/SysMangoIntermediateCA.crt 

- name: Update cert index
  become: yes
  command: /usr/sbin/update-ca-certificates