---

- name: Check if nagios service is running
  shell: docker service ls | awk '{print $2}' | grep nagios
  changed_when: false
  ignore_errors: true
  failed_when: nagios_status.rc == 2
  register: nagios_status

- name: Create nagios volume directory
  become: "yes"
  file:
    path: /srv/nfs/nagios
    mode: 0777
    state: directory
  run_once: true
  when: nagios_status.rc == 1

- name: Create nagios local config directory etc
  become: "yes"
  file:
    path: /srv/nfs/nagios/etc
    mode: 0777
    state: directory
  run_once: true
  when: nagios_status.rc == 1

- name: Create nagios local config directory var
  become: "yes"
  file:
    path: /srv/nfs/nagios/var
    mode: 0777
    state: directory
  run_once: true
  when: nagios_status.rc == 1

- name: Create nagios local config directory custom
  become: "yes"
  file:
    path: /srv/nfs/nagios/custom-plugins
    mode: 0777
    state: directory
  run_once: true
  when: nagios_status.rc == 1

- name: Deploy nagios service
  command: |
    docker service create -d --name nagios  \
    --network mangonet \
    --label traefik.port=80 \
    --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/nagios/etc,volume-opt=type=nfs,target=/opt/nagios/etc' \
    --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/nagios/var,volume-opt=type=nfs,target=/opt/nagios/var' \
    --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/nagios/custom-plugins,volume-opt=type=nfs,target=/opt/Custom-Nagios-Plugins' \
    -e MAIL_RELAY_HOST=smtp \
    -e NAGIOS_FQDN=nagios.sysmango.net \
    jasonrivers/nagios:latest
  run_once: true
  when: nagios_status.rc == 1
