---

- name: Install flannel package
  zypper:
    name: flannel
    state: present

- name: Configure flannel etcd key
  lineinfile:
    path: /etc/sysconfig/flanneld
    regexp: 'FLANNEL_ETCD_KEY'
    line: FLANNEL_ETCD_KEY="/sysmango/swarm/network"

- name: Configure flannel /sysmango/swarm/network/config
  command: etcdctl set /sysmango/swarm/network/config '{"Network":"172.16.0.0/16","SubnetLen":20, "Backend":{ "Type":"vxlan","Port":7890}}'

- name: Enable and start flanneld
  service:
    name: flanneld
    state: started
    enabled: "true"
