---

- name: Deploy smtp service
  hosts: docker-manager
  shell: docker service create --name smtp --network mangonet -e SYSTEM_TIMEZONE=America/New_York -e EMAIL=bostch@gmail.com -e EMAILPASS=awtusdlwnfexuujn -e MYNETWORKS="10.0.0.0/8 192.168.0.0/16 172.0.0.0/8" --publish 587:25  lylescott/postfix-gmail-relay 
  notify:


# - name: Register name with Route53
