---

- name: Add Tumbleweed CaaSP repoistory
  zypper_repository:
    name: CaaSP-repo
    repo: http://download.opensuse.org/repositories/devel:/CaaSP:/2.0:/ControllerNode/openSUSE_Tumbleweed/
    state: present
    auto_import_keys: yes
    enabled: yes
    autorefresh: yes
    runrefresh: yes

- name: Install Kubernetes components
  zypper:
    name: '{{ item }}'
    state: present
  with_items:
  - 'kubernetes-master'
  - 'docker_1_12_6'
  - 'kubernetes-common'
  - 'kubernetes-kubelet'
  - 'kubernetes-node'
  - 'kubernetes-client'
  - 'python-docker'
  - 'python2-docker'
  - 'kubernetes-kubeadm'
  - 'flannel'
  - 'etcd'

- name: Enable docker service
  service: 
    name: docker
    state: started
    enabled: yes

- name: Enable kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes
  notify: 
  - reboot linux
    