---

- name: Check if postgres service is running
  shell: docker service ls | awk '{print $2}' | grep postgres
  changed_when: false
  register: postgres_status
  failed_when: postgres_status.rc == 2


- name: Create volume directory
  hosts: nfs-server[0]
  become: yes
  file:
    path: /srv/nfs/postgres/pgdata
    state: directory
    mode: 777
  when: postgres_status|changed

- name: Deploy postgresql service
  hosts: docker-manager
  shell: docker service create -d --name postgres --network mangonet --mount type=bind,src=/srv/docker-volumes/postgres/pgdata,dst=/var/lib/postgresql/data --env PGDATA=/var/lib/postgresql/data/pgdata --replicas 1 registry.sysmango.net:5000/postgres:latest
  when: postgres_status|changed