---

- name: Register smtp name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: smtp.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true

- name: Register registry name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: registry.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true

- name: Register jenkins name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: jenkins.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true

- name: Register jira name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: jira.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true

- name: Register nagios name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: nagios.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true

- name: Register kibana name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: kibana.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.225,192.168.1.200
    overwrite: true
    wait: true
