---

- name: Register smtp name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: smtp.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.202
    overwrite: yes
    wait: yes


- name: Register registry name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: registry.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.202
    overwrite: yes
    wait: yes

- name: Register jenkins name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: jenkins.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.202
    overwrite: yes
    wait: yes

- name: Register jira name with Route53
  route53:
    state: present
    zone: sysmango.net
    record: jira.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.202
    overwrite: yes
    wait: yes